version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: lab-24-docker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "32000:3306"
    volumes:
      - mysql:/var/lib/mysql
  server:
    build:
      dockerfile: Dockerfile
    container_name: lab-24-docker-server
    restart: always
    depends_on:
      - mysql
    ports:
      - "5000"

volumes:
  mysql: